name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a branch que deseja publicar
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload de arquivos para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Certifique-se de que o caminho contém os arquivos HTML

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4
